

package sms;
import java.sql.*;
import javax.swing.JOptionPane;


public class frmStudent extends javax.swing.JInternalFrame {

    Connection cn;
    Statement st;
    ResultSet rs;
    PreparedStatement pst;
    public frmStudent() {
        initComponents();
        setSize(500,500);
        setLocation(200,200);
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/login","root","root");
            st = cn.createStatement();
            rs= st.executeQuery("select * from student");
             if(rs.next())
            {
                t1.setText(rs.getString("sid"));
                t2.setText(rs.getString("sname"));
                t3.setText(rs.getString("address"));
                t4.setText(rs.getString("phone"));
                 String x= rs.getString("gender");
                if(x.equals("male"))
                    jRadioButton1.setSelected(true);
                else
                    jRadioButton2.setSelected(true);

                t5.setText(rs.getString("dob"));
                jComboBox1.setSelectedItem(rs.getString("qualification"));
                t6.setText(rs.getString("city"));
                jComboBox2.setSelectedItem(rs.getString("state"));

            }
        }catch(Exception e1)
        {
            JOptionPane.showMessageDialog(this, e1);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t3 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        t5 = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        t7 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        getContentPane().setLayout(null);

        jLabel1.setText("sid");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 40, 20);

        jLabel2.setText("sname");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 50, 60, 20);

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(140, 20, 70, 20);

        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        getContentPane().add(t2);
        t2.setBounds(140, 50, 170, 20);

        jLabel3.setText("address");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 80, 60, 20);

        t3.setColumns(20);
        t3.setRows(5);
        jScrollPane1.setViewportView(t3);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(140, 80, 190, 50);

        jLabel4.setText("phone");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 150, 40, 20);
        getContentPane().add(t4);
        t4.setBounds(140, 150, 150, 20);

        jLabel6.setText("gender");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 180, 40, 20);

        t5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d/M/yy"))));
        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });
        getContentPane().add(t5);
        t5.setBounds(140, 210, 110, 20);

        jLabel7.setText("dob");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 210, 50, 20);

        jLabel8.setText("qualification");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 240, 60, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "B.E", "B.Tech", "M.E", "M.Tech" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(140, 240, 100, 22);

        jLabel9.setText("state");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 310, 34, 14);

        jLabel10.setText("city");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 280, 20, 14);
        getContentPane().add(t6);
        t6.setBounds(140, 280, 130, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gujarat", "Rajasthan", "Delhi", "Maharasthra", "UttarPradesh" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(140, 310, 130, 22);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(60, 350, 120, 30);

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(210, 350, 130, 30);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("male");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(140, 180, 60, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("female");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(200, 180, 57, 23);
        getContentPane().add(t7);
        t7.setBounds(340, 50, 110, 20);

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(460, 50, 75, 23);

        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(460, 80, 80, 23);

        jButton5.setText("Delete data");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(440, 110, 100, 20);

        jButton6.setText("Next");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(360, 350, 80, 30);

        jButton7.setText("Previous");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(450, 350, 90, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t5ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try
       {
            pst = cn.prepareStatement("insert into student values(?,?,?,?,?,?,?,?,?)");
            pst.setObject(1, t1.getText());
            pst.setObject(2, t2.getText());
            pst.setObject(3, t3.getText());
            pst.setObject(4, t4.getText());
            String gen ="";
            if(jRadioButton1.isSelected())
                gen="male";
            else if(jRadioButton2.isSelected())
                gen ="female";
            pst.setObject(5, gen);
            pst.setObject(6, t5.getValue());
            pst.setObject(7, jComboBox1.getSelectedItem());
            pst.setObject(8, t6.getText());
            pst.setObject(9,jComboBox2.getSelectedItem());
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this,"Data inserted");
       }catch(Exception e1)
       {
            JOptionPane.showMessageDialog(this, e1);
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try
        {
            t1.setText("");
            t2.setText("");
            t3.setText("");
            t4.setText("");
            t5.setText("");
            t6.setText("");

        }catch(Exception e1)
        {
            JOptionPane.showMessageDialog(this, e1);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try
        {
            
            rs = st.executeQuery("select * from student where sid = "+t7.getText()+"");
            if(rs.next())
            {
                t1.setText(rs.getString("sid"));
                t2.setText(rs.getString("sname"));
                t3.setText(rs.getString("address"));
                t4.setText(rs.getString("phone"));
                String x= rs.getString("gender");
                if(x.equals("male"))
                    jRadioButton1.setSelected(true);
                else
                    jRadioButton2.setSelected(true);

                t5.setText(rs.getString("dob"));
                jComboBox1.setSelectedItem(rs.getString("qualification"));
                t6.setText(rs.getString("city"));
                jComboBox2.setSelectedItem(rs.getString("state"));


                JOptionPane.showMessageDialog(this, "Search Completed");
            }

        }catch(Exception e1)
        {
            JOptionPane.showMessageDialog(this, e1);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try
        {
           pst = cn.prepareStatement("update student set sname = ?,address = ?, phone = ?,gender = ?,dob = ?, qualification = ?, city = ?, state = ? where sid = ?");
            pst.setObject(1,t2.getText());
            pst.setObject(2,t3.getText());
            pst.setObject(3,t4.getText());
            String gen = "";
            if(jRadioButton1.isSelected())
                gen = "male";
            else if(jRadioButton2.isSelected())
                    gen = "female";
            pst.setObject(4, gen);
            pst.setObject(5,t5.getText());
            pst.setObject(6,jComboBox1.getSelectedItem());
            pst.setObject(7,t6.getText());
            pst.setObject(8,jComboBox2.getSelectedItem());
            pst.setObject(9, t7.getText());
            pst.executeUpdate();


              JOptionPane.showMessageDialog(this, "Data updated");

        }catch(Exception e1)
        {
            JOptionPane.showMessageDialog(this, e1);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       try
       {
           pst = cn.prepareStatement("delete from student where sid = ?");
           pst.setObject(1, t1.getText());
           pst.executeUpdate();

           JOptionPane.showMessageDialog(this, "Data deleted");
       }catch(Exception e1)
       {
          JOptionPane.showMessageDialog(this, e1);
       }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try
        {
            
            if(rs.next())
            {
                t1.setText(rs.getString("sid"));
                t2.setText(rs.getString("sname"));
                t3.setText(rs.getString("address"));
                t4.setText(rs.getString("phone"));
                 String x= rs.getString("gender");
                if(x.equals("male"))
                    jRadioButton1.setSelected(true);
                else
                    jRadioButton2.setSelected(true);

                t5.setText(rs.getString("dob"));
                jComboBox1.setSelectedItem(rs.getString("qualification"));
                t6.setText(rs.getString("city"));
                jComboBox2.setSelectedItem(rs.getString("state"));

            }
        }catch(Exception e1)
        {
            JOptionPane.showMessageDialog(this, e1);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try{


        if(rs.previous())
            {
                t1.setText(rs.getString("sid"));
                t2.setText(rs.getString("sname"));
                t3.setText(rs.getString("address"));
                t4.setText(rs.getString("phone"));
                 String x= rs.getString("gender");
                if(x.equals("male"))
                    jRadioButton1.setSelected(true);
                else
                    jRadioButton2.setSelected(true);

                t5.setText(rs.getString("dob"));
                jComboBox1.setSelectedItem(rs.getString("qualification"));
                t6.setText(rs.getString("city"));
                jComboBox2.setSelectedItem(rs.getString("state"));

            }}catch(Exception e1)
            {
                JOptionPane.showMessageDialog(this, e1);
            }
    }//GEN-LAST:event_jButton7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextArea t3;
    private javax.swing.JTextField t4;
    private javax.swing.JFormattedTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    // End of variables declaration//GEN-END:variables

}
